/* ==================================================================== */
/* ============================= INCLUDES ============================= */
/* ==================================================================== */

#include "gcanUtils.h"

/* ==================================================================== */
/* ========================= LOCAL VARIABLES ========================== */
/* ==================================================================== */

FLOAT_CAN_STRUCT *cellVoltageParams[NUM_CELL_MON][NUM_CELLS_PER_CELL_MONITOR] =
{
    {&module1Cell1Voltage_V, &module1Cell2Voltage_V, &module1Cell3Voltage_V, &module1Cell4Voltage_V, &module1Cell5Voltage_V, &module1Cell6Voltage_V, &module1Cell7Voltage_V, &module1Cell8Voltage_V, &module1Cell9Voltage_V, &module1Cell10Voltage_V, &module1Cell11Voltage_V, &module1Cell12Voltage_V, &module1Cell13Voltage_V, &module1Cell14Voltage_V},
    {&module2Cell1Voltage_V, &module2Cell2Voltage_V, &module2Cell3Voltage_V, &module2Cell4Voltage_V, &module2Cell5Voltage_V, &module2Cell6Voltage_V, &module2Cell7Voltage_V, &module2Cell8Voltage_V, &module2Cell9Voltage_V, &module2Cell10Voltage_V, &module2Cell11Voltage_V, &module2Cell12Voltage_V, &module2Cell13Voltage_V, &module2Cell14Voltage_V},
    {&module3Cell1Voltage_V, &module3Cell2Voltage_V, &module3Cell3Voltage_V, &module3Cell4Voltage_V, &module3Cell5Voltage_V, &module3Cell6Voltage_V, &module3Cell7Voltage_V, &module3Cell8Voltage_V, &module3Cell9Voltage_V, &module3Cell10Voltage_V, &module3Cell11Voltage_V, &module3Cell12Voltage_V, &module3Cell13Voltage_V, &module3Cell14Voltage_V},
    {&module4Cell1Voltage_V, &module4Cell2Voltage_V, &module4Cell3Voltage_V, &module4Cell4Voltage_V, &module4Cell5Voltage_V, &module4Cell6Voltage_V, &module4Cell7Voltage_V, &module4Cell8Voltage_V, &module4Cell9Voltage_V, &module4Cell10Voltage_V, &module4Cell11Voltage_V, &module4Cell12Voltage_V, &module4Cell13Voltage_V, &module4Cell14Voltage_V},
    {&module5Cell1Voltage_V, &module5Cell2Voltage_V, &module5Cell3Voltage_V, &module5Cell4Voltage_V, &module5Cell5Voltage_V, &module5Cell6Voltage_V, &module5Cell7Voltage_V, &module5Cell8Voltage_V, &module5Cell9Voltage_V, &module5Cell10Voltage_V, &module5Cell11Voltage_V, &module5Cell12Voltage_V, &module5Cell13Voltage_V, &module5Cell14Voltage_V},
    {&module6Cell1Voltage_V, &module6Cell2Voltage_V, &module6Cell3Voltage_V, &module6Cell4Voltage_V, &module6Cell5Voltage_V, &module6Cell6Voltage_V, &module6Cell7Voltage_V, &module6Cell8Voltage_V, &module6Cell9Voltage_V, &module6Cell10Voltage_V, &module6Cell11Voltage_V, &module6Cell12Voltage_V, &module6Cell13Voltage_V, &module6Cell14Voltage_V},
    {&module7Cell1Voltage_V, &module7Cell2Voltage_V, &module7Cell3Voltage_V, &module7Cell4Voltage_V, &module7Cell5Voltage_V, &module7Cell6Voltage_V, &module7Cell7Voltage_V, &module7Cell8Voltage_V, &module7Cell9Voltage_V, &module7Cell10Voltage_V, &module7Cell11Voltage_V, &module7Cell12Voltage_V, &module7Cell13Voltage_V, &module7Cell14Voltage_V},
    {&module8Cell1Voltage_V, &module8Cell2Voltage_V, &module8Cell3Voltage_V, &module8Cell4Voltage_V, &module8Cell5Voltage_V, &module8Cell6Voltage_V, &module8Cell7Voltage_V, &module8Cell8Voltage_V, &module8Cell9Voltage_V, &module8Cell10Voltage_V, &module8Cell11Voltage_V, &module8Cell12Voltage_V, &module8Cell13Voltage_V, &module8Cell14Voltage_V},
    {&module9Cell1Voltage_V, &module9Cell2Voltage_V, &module9Cell3Voltage_V, &module9Cell4Voltage_V, &module9Cell5Voltage_V, &module9Cell6Voltage_V, &module9Cell7Voltage_V, &module9Cell8Voltage_V, &module9Cell9Voltage_V, &module9Cell10Voltage_V, &module9Cell11Voltage_V, &module9Cell12Voltage_V, &module9Cell13Voltage_V, &module9Cell14Voltage_V},
    {&module10Cell1Voltage_V, &module10Cell2Voltage_V, &module10Cell3Voltage_V, &module10Cell4Voltage_V, &module10Cell5Voltage_V, &module10Cell6Voltage_V, &module10Cell7Voltage_V, &module10Cell8Voltage_V, &module10Cell9Voltage_V, &module10Cell10Voltage_V, &module10Cell11Voltage_V, &module10Cell12Voltage_V, &module10Cell13Voltage_V, &module10Cell14Voltage_V}
};

FLOAT_CAN_STRUCT *cellTempParams[NUM_CELL_MON][NUM_CELLS_PER_CELL_MONITOR] =
{
    {&module1Cell1Temperature_C, &module1Cell2Temperature_C, &module1Cell3Temperature_C, &module1Cell4Temperature_C, &module1Cell5Temperature_C, &module1Cell6Temperature_C, &module1Cell7Temperature_C, &module1Cell8Temperature_C, &module1Cell9Temperature_C, &module1Cell10Temperature_C, &module1Cell11Temperature_C, &module1Cell12Temperature_C, &module1Cell13Temperature_C, &module1Cell14Temperature_C},
    {&module2Cell1Temperature_C, &module2Cell2Temperature_C, &module2Cell3Temperature_C, &module2Cell4Temperature_C, &module2Cell5Temperature_C, &module2Cell6Temperature_C, &module2Cell7Temperature_C, &module2Cell8Temperature_C, &module2Cell9Temperature_C, &module2Cell10Temperature_C, &module2Cell11Temperature_C, &module2Cell12Temperature_C, &module2Cell13Temperature_C, &module2Cell14Temperature_C},
    {&module3Cell1Temperature_C, &module3Cell2Temperature_C, &module3Cell3Temperature_C, &module3Cell4Temperature_C, &module3Cell5Temperature_C, &module3Cell6Temperature_C, &module3Cell7Temperature_C, &module3Cell8Temperature_C, &module3Cell9Temperature_C, &module3Cell10Temperature_C, &module3Cell11Temperature_C, &module3Cell12Temperature_C, &module3Cell13Temperature_C, &module3Cell14Temperature_C},
    {&module4Cell1Temperature_C, &module4Cell2Temperature_C, &module4Cell3Temperature_C, &module4Cell4Temperature_C, &module4Cell5Temperature_C, &module4Cell6Temperature_C, &module4Cell7Temperature_C, &module4Cell8Temperature_C, &module4Cell9Temperature_C, &module4Cell10Temperature_C, &module4Cell11Temperature_C, &module4Cell12Temperature_C, &module4Cell13Temperature_C, &module4Cell14Temperature_C},
    {&module5Cell1Temperature_C, &module5Cell2Temperature_C, &module5Cell3Temperature_C, &module5Cell4Temperature_C, &module5Cell5Temperature_C, &module5Cell6Temperature_C, &module5Cell7Temperature_C, &module5Cell8Temperature_C, &module5Cell9Temperature_C, &module5Cell10Temperature_C, &module5Cell11Temperature_C, &module5Cell12Temperature_C, &module5Cell13Temperature_C, &module5Cell14Temperature_C},
    {&module6Cell1Temperature_C, &module6Cell2Temperature_C, &module6Cell3Temperature_C, &module6Cell4Temperature_C, &module6Cell5Temperature_C, &module6Cell6Temperature_C, &module6Cell7Temperature_C, &module6Cell8Temperature_C, &module6Cell9Temperature_C, &module6Cell10Temperature_C, &module6Cell11Temperature_C, &module6Cell12Temperature_C, &module6Cell13Temperature_C, &module6Cell14Temperature_C},
    {&module7Cell1Temperature_C, &module7Cell2Temperature_C, &module7Cell3Temperature_C, &module7Cell4Temperature_C, &module7Cell5Temperature_C, &module7Cell6Temperature_C, &module7Cell7Temperature_C, &module7Cell8Temperature_C, &module7Cell9Temperature_C, &module7Cell10Temperature_C, &module7Cell11Temperature_C, &module7Cell12Temperature_C, &module7Cell13Temperature_C, &module7Cell14Temperature_C},
    {&module8Cell1Temperature_C, &module8Cell2Temperature_C, &module8Cell3Temperature_C, &module8Cell4Temperature_C, &module8Cell5Temperature_C, &module8Cell6Temperature_C, &module8Cell7Temperature_C, &module8Cell8Temperature_C, &module8Cell9Temperature_C, &module8Cell10Temperature_C, &module8Cell11Temperature_C, &module8Cell12Temperature_C, &module8Cell13Temperature_C, &module8Cell14Temperature_C},
    {&module9Cell1Temperature_C, &module9Cell2Temperature_C, &module9Cell3Temperature_C, &module9Cell4Temperature_C, &module9Cell5Temperature_C, &module9Cell6Temperature_C, &module9Cell7Temperature_C, &module9Cell8Temperature_C, &module9Cell9Temperature_C, &module9Cell10Temperature_C, &module9Cell11Temperature_C, &module9Cell12Temperature_C, &module9Cell13Temperature_C, &module9Cell14Temperature_C},
    {&module10Cell1Temperature_C, &module10Cell2Temperature_C, &module10Cell3Temperature_C, &module10Cell4Temperature_C, &module10Cell5Temperature_C, &module10Cell6Temperature_C, &module10Cell7Temperature_C, &module10Cell8Temperature_C, &module10Cell9Temperature_C, &module10Cell10Temperature_C, &module10Cell11Temperature_C, &module10Cell12Temperature_C, &module10Cell13Temperature_C, &module10Cell14Temperature_C}
};

FLOAT_CAN_STRUCT *cellStatParams[NUM_CELL_MON][NUM_STAT_PARAMS] =
{
    {&module1MaxCellVoltage_V, &module1MinCellVoltage_V, &module1AvgCellVoltage_V, &module1DieTemperature_C, &module1MaxCellTemperature_C, &module1MinCellTemperature_C, &module1AvgCellTemperature_C, &module1BoardTemperature_C},
    {&module2MaxCellVoltage_V, &module2MinCellVoltage_V, &module2AvgCellVoltage_V, &module2DieTemperature_C, &module2MaxCellTemperature_C, &module2MinCellTemperature_C, &module2AvgCellTemperature_C, &module2BoardTemperature_C},
    {&module3MaxCellVoltage_V, &module3MinCellVoltage_V, &module3AvgCellVoltage_V, &module3DieTemperature_C, &module3MaxCellTemperature_C, &module3MinCellTemperature_C, &module3AvgCellTemperature_C, &module3BoardTemperature_C},
    {&module4MaxCellVoltage_V, &module4MinCellVoltage_V, &module4AvgCellVoltage_V, &module4DieTemperature_C, &module4MaxCellTemperature_C, &module4MinCellTemperature_C, &module4AvgCellTemperature_C, &module4BoardTemperature_C},
    {&module5MaxCellVoltage_V, &module5MinCellVoltage_V, &module5AvgCellVoltage_V, &module5DieTemperature_C, &module5MaxCellTemperature_C, &module5MinCellTemperature_C, &module5AvgCellTemperature_C, &module5BoardTemperature_C},
    {&module6MaxCellVoltage_V, &module6MinCellVoltage_V, &module6AvgCellVoltage_V, &module6DieTemperature_C, &module6MaxCellTemperature_C, &module6MinCellTemperature_C, &module6AvgCellTemperature_C, &module6BoardTemperature_C},
    {&module7MaxCellVoltage_V, &module7MinCellVoltage_V, &module7AvgCellVoltage_V, &module7DieTemperature_C, &module7MaxCellTemperature_C, &module7MinCellTemperature_C, &module7AvgCellTemperature_C, &module7BoardTemperature_C},
    {&module8MaxCellVoltage_V, &module8MinCellVoltage_V, &module8AvgCellVoltage_V, &module8DieTemperature_C, &module8MaxCellTemperature_C, &module8MinCellTemperature_C, &module8AvgCellTemperature_C, &module8BoardTemperature_C},
    {&module9MaxCellVoltage_V, &module9MinCellVoltage_V, &module9AvgCellVoltage_V, &module9DieTemperature_C, &module9MaxCellTemperature_C, &module9MinCellTemperature_C, &module9AvgCellTemperature_C, &module9BoardTemperature_C},
    {&module10MaxCellVoltage_V, &module10MinCellVoltage_V, &module10AvgCellVoltage_V, &module10DieTemperature_C, &module10MaxCellTemperature_C, &module10MinCellTemperature_C, &module10AvgCellTemperature_C, &module10BoardTemperature_C}
};
