/* ==================================================================== */
/* ============================= INCLUDES ============================= */
/* ==================================================================== */

#include "gcanUtils.h"

/* ==================================================================== */
/* ========================= LOCAL VARIABLES ========================== */
/* ==================================================================== */

const FLOAT_CAN_STRUCT *cellVoltageParams[NUM_CELL_MON][NUM_CELLS_PER_CELL_MONITOR] =
{
    {&segment1Cell1Voltage_V, &segment1Cell2Voltage_V, &segment1Cell3Voltage_V, &segment1Cell4Voltage_V, &segment1Cell5Voltage_V, &segment1Cell6Voltage_V, &segment1Cell7Voltage_V, &segment1Cell8Voltage_V, &segment1Cell9Voltage_V, &segment1Cell10Voltage_V, &segment1Cell11Voltage_V, &segment1Cell12Voltage_V, &segment1Cell13Voltage_V, &segment1Cell14Voltage_V},
    {&segment2Cell1Voltage_V, &segment2Cell2Voltage_V, &segment2Cell3Voltage_V, &segment2Cell4Voltage_V, &segment2Cell5Voltage_V, &segment2Cell6Voltage_V, &segment2Cell7Voltage_V, &segment2Cell8Voltage_V, &segment2Cell9Voltage_V, &segment2Cell10Voltage_V, &segment2Cell11Voltage_V, &segment2Cell12Voltage_V, &segment2Cell13Voltage_V, &segment2Cell14Voltage_V},
    {&segment3Cell1Voltage_V, &segment3Cell2Voltage_V, &segment3Cell3Voltage_V, &segment3Cell4Voltage_V, &segment3Cell5Voltage_V, &segment3Cell6Voltage_V, &segment3Cell7Voltage_V, &segment3Cell8Voltage_V, &segment3Cell9Voltage_V, &segment3Cell10Voltage_V, &segment3Cell11Voltage_V, &segment3Cell12Voltage_V, &segment3Cell13Voltage_V, &segment3Cell14Voltage_V},
    {&segment4Cell1Voltage_V, &segment4Cell2Voltage_V, &segment4Cell3Voltage_V, &segment4Cell4Voltage_V, &segment4Cell5Voltage_V, &segment4Cell6Voltage_V, &segment4Cell7Voltage_V, &segment4Cell8Voltage_V, &segment4Cell9Voltage_V, &segment4Cell10Voltage_V, &segment4Cell11Voltage_V, &segment4Cell12Voltage_V, &segment4Cell13Voltage_V, &segment4Cell14Voltage_V},
    {&segment5Cell1Voltage_V, &segment5Cell2Voltage_V, &segment5Cell3Voltage_V, &segment5Cell4Voltage_V, &segment5Cell5Voltage_V, &segment5Cell6Voltage_V, &segment5Cell7Voltage_V, &segment5Cell8Voltage_V, &segment5Cell9Voltage_V, &segment5Cell10Voltage_V, &segment5Cell11Voltage_V, &segment5Cell12Voltage_V, &segment5Cell13Voltage_V, &segment5Cell14Voltage_V},
    {&segment6Cell1Voltage_V, &segment6Cell2Voltage_V, &segment6Cell3Voltage_V, &segment6Cell4Voltage_V, &segment6Cell5Voltage_V, &segment6Cell6Voltage_V, &segment6Cell7Voltage_V, &segment6Cell8Voltage_V, &segment6Cell9Voltage_V, &segment6Cell10Voltage_V, &segment6Cell11Voltage_V, &segment6Cell12Voltage_V, &segment6Cell13Voltage_V, &segment6Cell14Voltage_V},
    {&segment7Cell1Voltage_V, &segment7Cell2Voltage_V, &segment7Cell3Voltage_V, &segment7Cell4Voltage_V, &segment7Cell5Voltage_V, &segment7Cell6Voltage_V, &segment7Cell7Voltage_V, &segment7Cell8Voltage_V, &segment7Cell9Voltage_V, &segment7Cell10Voltage_V, &segment7Cell11Voltage_V, &segment7Cell12Voltage_V, &segment7Cell13Voltage_V, &segment7Cell14Voltage_V},
    {&segment8Cell1Voltage_V, &segment8Cell2Voltage_V, &segment8Cell3Voltage_V, &segment8Cell4Voltage_V, &segment8Cell5Voltage_V, &segment8Cell6Voltage_V, &segment8Cell7Voltage_V, &segment8Cell8Voltage_V, &segment8Cell9Voltage_V, &segment8Cell10Voltage_V, &segment8Cell11Voltage_V, &segment8Cell12Voltage_V, &segment8Cell13Voltage_V, &segment8Cell14Voltage_V},
    {&segment9Cell1Voltage_V, &segment9Cell2Voltage_V, &segment9Cell3Voltage_V, &segment9Cell4Voltage_V, &segment9Cell5Voltage_V, &segment9Cell6Voltage_V, &segment9Cell7Voltage_V, &segment9Cell8Voltage_V, &segment9Cell9Voltage_V, &segment9Cell10Voltage_V, &segment9Cell11Voltage_V, &segment9Cell12Voltage_V, &segment9Cell13Voltage_V, &segment9Cell14Voltage_V},
    {&segment10Cell1Voltage_V, &segment10Cell2Voltage_V, &segment10Cell3Voltage_V, &segment10Cell4Voltage_V, &segment10Cell5Voltage_V, &segment10Cell6Voltage_V, &segment10Cell7Voltage_V, &segment10Cell8Voltage_V, &segment10Cell9Voltage_V, &segment10Cell10Voltage_V, &segment10Cell11Voltage_V, &segment10Cell12Voltage_V, &segment10Cell13Voltage_V, &segment10Cell14Voltage_V}
};

const FLOAT_CAN_STRUCT *cellTempParams[NUM_CELL_MON][NUM_CELLS_PER_CELL_MONITOR] =
{
    {&segment1Cell1Temperature_C, &segment1Cell2Temperature_C, &segment1Cell3Temperature_C, &segment1Cell4Temperature_C, &segment1Cell5Temperature_C, &segment1Cell6Temperature_C, &segment1Cell7Temperature_C, &segment1Cell8Temperature_C, &segment1Cell9Temperature_C, &segment1Cell10Temperature_C, &segment1Cell11Temperature_C, &segment1Cell12Temperature_C, &segment1Cell13Temperature_C, &segment1Cell14Temperature_C},
    {&segment2Cell1Temperature_C, &segment2Cell2Temperature_C, &segment2Cell3Temperature_C, &segment2Cell4Temperature_C, &segment2Cell5Temperature_C, &segment2Cell6Temperature_C, &segment2Cell7Temperature_C, &segment2Cell8Temperature_C, &segment2Cell9Temperature_C, &segment2Cell10Temperature_C, &segment2Cell11Temperature_C, &segment2Cell12Temperature_C, &segment2Cell13Temperature_C, &segment2Cell14Temperature_C},
    {&segment3Cell1Temperature_C, &segment3Cell2Temperature_C, &segment3Cell3Temperature_C, &segment3Cell4Temperature_C, &segment3Cell5Temperature_C, &segment3Cell6Temperature_C, &segment3Cell7Temperature_C, &segment3Cell8Temperature_C, &segment3Cell9Temperature_C, &segment3Cell10Temperature_C, &segment3Cell11Temperature_C, &segment3Cell12Temperature_C, &segment3Cell13Temperature_C, &segment3Cell14Temperature_C},
    {&segment4Cell1Temperature_C, &segment4Cell2Temperature_C, &segment4Cell3Temperature_C, &segment4Cell4Temperature_C, &segment4Cell5Temperature_C, &segment4Cell6Temperature_C, &segment4Cell7Temperature_C, &segment4Cell8Temperature_C, &segment4Cell9Temperature_C, &segment4Cell10Temperature_C, &segment4Cell11Temperature_C, &segment4Cell12Temperature_C, &segment4Cell13Temperature_C, &segment4Cell14Temperature_C},
    {&segment5Cell1Temperature_C, &segment5Cell2Temperature_C, &segment5Cell3Temperature_C, &segment5Cell4Temperature_C, &segment5Cell5Temperature_C, &segment5Cell6Temperature_C, &segment5Cell7Temperature_C, &segment5Cell8Temperature_C, &segment5Cell9Temperature_C, &segment5Cell10Temperature_C, &segment5Cell11Temperature_C, &segment5Cell12Temperature_C, &segment5Cell13Temperature_C, &segment5Cell14Temperature_C},
    {&segment6Cell1Temperature_C, &segment6Cell2Temperature_C, &segment6Cell3Temperature_C, &segment6Cell4Temperature_C, &segment6Cell5Temperature_C, &segment6Cell6Temperature_C, &segment6Cell7Temperature_C, &segment6Cell8Temperature_C, &segment6Cell9Temperature_C, &segment6Cell10Temperature_C, &segment6Cell11Temperature_C, &segment6Cell12Temperature_C, &segment6Cell13Temperature_C, &segment6Cell14Temperature_C},
    {&segment7Cell1Temperature_C, &segment7Cell2Temperature_C, &segment7Cell3Temperature_C, &segment7Cell4Temperature_C, &segment7Cell5Temperature_C, &segment7Cell6Temperature_C, &segment7Cell7Temperature_C, &segment7Cell8Temperature_C, &segment7Cell9Temperature_C, &segment7Cell10Temperature_C, &segment7Cell11Temperature_C, &segment7Cell12Temperature_C, &segment7Cell13Temperature_C, &segment7Cell14Temperature_C},
    {&segment8Cell1Temperature_C, &segment8Cell2Temperature_C, &segment8Cell3Temperature_C, &segment8Cell4Temperature_C, &segment8Cell5Temperature_C, &segment8Cell6Temperature_C, &segment8Cell7Temperature_C, &segment8Cell8Temperature_C, &segment8Cell9Temperature_C, &segment8Cell10Temperature_C, &segment8Cell11Temperature_C, &segment8Cell12Temperature_C, &segment8Cell13Temperature_C, &segment8Cell14Temperature_C},
    {&segment9Cell1Temperature_C, &segment9Cell2Temperature_C, &segment9Cell3Temperature_C, &segment9Cell4Temperature_C, &segment9Cell5Temperature_C, &segment9Cell6Temperature_C, &segment9Cell7Temperature_C, &segment9Cell8Temperature_C, &segment9Cell9Temperature_C, &segment9Cell10Temperature_C, &segment9Cell11Temperature_C, &segment9Cell12Temperature_C, &segment9Cell13Temperature_C, &segment9Cell14Temperature_C},
    {&segment10Cell1Temperature_C, &segment10Cell2Temperature_C, &segment10Cell3Temperature_C, &segment10Cell4Temperature_C, &segment10Cell5Temperature_C, &segment10Cell6Temperature_C, &segment10Cell7Temperature_C, &segment10Cell8Temperature_C, &segment10Cell9Temperature_C, &segment10Cell10Temperature_C, &segment10Cell11Temperature_C, &segment10Cell12Temperature_C, &segment10Cell13Temperature_C, &segment10Cell14Temperature_C}
};

const FLOAT_CAN_STRUCT *cellStatParams[NUM_CELL_MON][NUM_STAT_PARAMS] =
{
    {&segment1MaxCellVoltage_V, &segment1MinCellVoltage_V, &segment1AvgCellVoltage_V, &segment1DieTemperature_C, &segment1MaxCellTemperature_C, &segment1MinCellTemperature_C, &segment1AvgCellTemperature_C, &segment1BoardTemperature_C},
    {&segment2MaxCellVoltage_V, &segment2MinCellVoltage_V, &segment2AvgCellVoltage_V, &segment2DieTemperature_C, &segment2MaxCellTemperature_C, &segment2MinCellTemperature_C, &segment2AvgCellTemperature_C, &segment2BoardTemperature_C},
    {&segment3MaxCellVoltage_V, &segment3MinCellVoltage_V, &segment3AvgCellVoltage_V, &segment3DieTemperature_C, &segment3MaxCellTemperature_C, &segment3MinCellTemperature_C, &segment3AvgCellTemperature_C, &segment3BoardTemperature_C},
    {&segment4MaxCellVoltage_V, &segment4MinCellVoltage_V, &segment4AvgCellVoltage_V, &segment4DieTemperature_C, &segment4MaxCellTemperature_C, &segment4MinCellTemperature_C, &segment4AvgCellTemperature_C, &segment4BoardTemperature_C},
    {&segment5MaxCellVoltage_V, &segment5MinCellVoltage_V, &segment5AvgCellVoltage_V, &segment5DieTemperature_C, &segment5MaxCellTemperature_C, &segment5MinCellTemperature_C, &segment5AvgCellTemperature_C, &segment5BoardTemperature_C},
    {&segment6MaxCellVoltage_V, &segment6MinCellVoltage_V, &segment6AvgCellVoltage_V, &segment6DieTemperature_C, &segment6MaxCellTemperature_C, &segment6MinCellTemperature_C, &segment6AvgCellTemperature_C, &segment6BoardTemperature_C},
    {&segment7MaxCellVoltage_V, &segment7MinCellVoltage_V, &segment7AvgCellVoltage_V, &segment7DieTemperature_C, &segment7MaxCellTemperature_C, &segment7MinCellTemperature_C, &segment7AvgCellTemperature_C, &segment7BoardTemperature_C},
    {&segment8MaxCellVoltage_V, &segment8MinCellVoltage_V, &segment8AvgCellVoltage_V, &segment8DieTemperature_C, &segment8MaxCellTemperature_C, &segment8MinCellTemperature_C, &segment8AvgCellTemperature_C, &segment8BoardTemperature_C},
    {&segment9MaxCellVoltage_V, &segment9MinCellVoltage_V, &segment9AvgCellVoltage_V, &segment9DieTemperature_C, &segment9MaxCellTemperature_C, &segment9MinCellTemperature_C, &segment9AvgCellTemperature_C, &segment9BoardTemperature_C},
    {&segment10MaxCellVoltage_V, &segment10MinCellVoltage_V, &segment10AvgCellVoltage_V, &segment10DieTemperature_C, &segment10MaxCellTemperature_C, &segment10MinCellTemperature_C, &segment10AvgCellTemperature_C, &segment10BoardTemperature_C}
};
